### ISSUE TITLE
Compilation fails if result type is not the last in visitor's type parameters list

### ISSUE THREAD

**Issue by avakhrenev** [sviperll/adt4j#25]
With adt4j-1.3
```java
@GenerateValueClassForVisitor
@Visitor(resultVariableName = "R")
public interface ValueVisitor<R, T> {
    R value(T value);
}
```
is falls with 
```
java.lang.ArrayIndexOutOfBoundsException: 1
      at java.util.Arrays$ArrayList.get(Arrays.java:3841)
      at com.github.sviperll.adt4j.model.util.ValueVisitorInterfaceModel.narrowType(ValueVisitorInterfaceModel.java:182)
      at com.github.sviperll.adt4j.model.util.ValueVisitorInterfaceModel.narrowType(ValueVisitorInterfaceModel.java:173)
      at com.github.sviperll.adt4j.model.ValueClassModel.buildCaseClass(ValueClassModel.java:186)
      at com.github.sviperll.adt4j.model.ValueClassModel.buildCaseClasses(ValueClassModel.java:163)
      at com.github.sviperll.adt4j.model.ValueClassModel.createMethodBuilder(ValueClassModel.java:90)
      at com.github.sviperll.adt4j.model.ValueClassModelFactory.createValueClass(ValueClassModelFactory.java:195)
      at com.github.sviperll.adt4j.model.ValueClassModelFactory.createValueClass(ValueClassModelFactory.java:65)
      at com.github.sviperll.adt4j.GenerateValueClassForVisitorProcessor.processElements(GenerateValueClassForVisitorProcessor.java:101)
      at com.github.sviperll.adt4j.GenerateValueClassForVisitorProcessor.process(GenerateValueClassForVisitorProcessor.java:84)
      at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
      at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
      at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
```
while the same with different type parameter order
```java
@GenerateValueClassForVisitor
@Visitor(resultVariableName = "R")
public interface ValueVisitor<T, R> {
    R value(T value);
}
```
compiles fine.

**Comment by sviperll** [comment]
Thank you for your report. I'll try to look into it on Monday.
